### ISSUE TITLE
Grammars can cause infinite loops

### ISSUE THREAD

**Issue by antimatter15** [bijection/nearley-playground#3]
```
bob -> bob | jill
jill -> "bob"
```

If you add a test with "bob", the page hangs. There should probably be something that catches grammars that seem to take too long to run, or to run the grammars on a webworker so it doesn't interrupt the user.

**Comment by fjorgemota** [comment]
The worst thing about this issue is that, because the playground saves the state of the editor in the `localStorage`, if a grammar/test causes an infinite loop, the whole site become inacessible to all future visits from that browser.

To solve that, I have to access https://omrelli.ug/, open the Chrome's developer tools, go to the "Application" tab and, there, clean all the storage related to the site (which causes the playground to be reseted too), which really sucks.

As the problem does not seem to be in the playground itself (I suppose the infinite loop is caused by the nearley parser, which, yeah, may have infinite loops too (edit: confirmed, the bug is in Nearley and [an issue was already opened](https://github.com/Hardmath123/nearley/issues/167))), I have a few ideas to solve that problem here in the playground:

- Add an option to not save/restore the state of the editor automatically (I think it would be an easy task);
- Webworkers - Probably with an option to `terminate()` that webworker easily (a more difficult task, but not too hard);
- Adapt Nearley to do the parsing in a pausable way (calling `step()` or another method many times to do the parsing step by step, for example) (I think it would be a really hard task);

By the way, that's it.

Thanks for the great playground! :)

**Comment by cimi** [comment]
> To solve that, I have to access https://omrelli.ug/, open the Chrome's developer tools, go to the "Application" tab and, there, clean all the storage related to the site (which causes the playground to be reseted too), which really sucks.

Incognito mode also works, for what it's worth. Great description of the issue!

**Comment by fjorgemota** [comment]
Yeah, sure. I noted it just after posting that issue. =)

Thanks.

**Comment by george-norris-salesforce** [comment]
Would be awesome if the playground was run with a webworker and kill the webworker if there is a loop. This keeps happening to me too..

**Comment by george-norris-salesforce** [comment]
Problem with using Incognito, it that is doesn't solve the issue in the main browser. If you open main browser it still crashes..
